[aws]
disabled = true

[directory]
truncate_to_repo = false

[gcloud]
disabled = true

[nodejs]
format = "using [$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "

[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[battery]
full_symbol = "🔋 "

[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 20
style = "bold yellow"
discharging_symbol = "💀 "

[php]
format = "via [$symbol$version]($style) "
symbol = "🐘 "
style = "147 bold"
disabled = false